name:                frontend
version:             0.1.0.0
github:              "polyfooly/ib2/frontend"
license:             Apache-2.0
license-file:        LICENSE
author:              "Kyryl Vlasov"
maintainer:          "vlaso.kirill2011@gmail.com"
copyright:           "2019 Kyryl Vlasov"

ghc-options: -Wall -Wcompat -Wincomplete-uni-patterns -Widentities  -Wno-simplifiable-class-constraints
ghcjs-options: -dedupe -fsimpl-tick-factor=200
cpp-options: -DGHCJS_BROWSER

dependencies:
- base
- servant-reflex
- containers
- reflex
- reflex-dom
- reflex-dom-contrib
- aeson
- time
- text

- common


library:
  source-dirs: src/lib

executables:
  webapp:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - frontend
