language: nix
script: |
  nix-shell -A shells.ghc --run "cabal new-build all -j1" && \
  nix-shell -A shells.ghcjs --run "cabal new-build --project-file=cabal-ghcjs.project --builddir=dist-js all -j1"
