name:                node
version:             0.1.0.0
github:              "polyfooly/ib2/backend/node"
license:             Apache-2.0
license-file:        LICENSE
author:              "Kyryl Vlasov"
maintainer:          "vlaso.kirill2011@gmail.com"
copyright:           "2019 Kyryl Vlasov"

ghc-options: -Werror -Wall -Wcompat -Wincomplete-uni-patterns -Widentities  -Wno-simplifiable-class-constraints
#ghcjs-options: -dedupe
#cpp-options: -DGHCJS_BROWSER

dependencies:
- base
- servant
- servant-server
- servant-reflex
- servant-client
- aeson
- wai
- warp
- http-client
- http-reverse-proxy
- http-types

- common
- frontendhost

library:
  source-dirs: src/lib

executables:
  node-service:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - node
