name:                common
version:             0.1.0.0
github:              "polyfooly/ib2/common"
license:             Apache-2.0
license-file:        LICENSE
author:              "Kyryl Vlasov"
maintainer:          "vlaso.kirill2011@gmail.com"
copyright:           "2019 Kyryl Vlasov"

ghc-options: -Wall -Wcompat -Wincomplete-uni-patterns -Widentities  -Wno-simplifiable-class-constraints
ghcjs-options: -dedupe
cpp-options: -DGHCJS_BROWSER

dependencies:
- base
- time
- aeson
- text
- servant-server
- servant-pagination


library:
  source-dirs: 
    - src/lib
    - ../backend/posts/src/lib
    - ../backend/lib/src
  other-modules:
    #- IB2.Service.Server
    - IB2.Service.Server.Types
    - Posts.Types
    - Posts.API
  exposed-modules:
    - IB2.Common.API
    - IB2.Common.Types
